version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - "6379:6379"
  graphs:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - db
  ogriner:
    build: "./docker-ogriner"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
